### ISSUE TITLE
Explain the difference with Spotless

### ISSUE THREAD

**Issue by LifeIsStrange** [autostyle/autostyle#20]
I have read both Readmes and autostyle seems to be an unmaintained older version of spotless ?
Does it has any advantage versus spotless ?

**Comment by vlsi** [comment]
@LifeIsStrange , thanks for asking.

Autostyle changelog lists the updates: https://github.com/autostyle/autostyle/blob/master/CHANGES.md

> unmaintained

That depends on the definition of "unmaintained".
Autostyle works for me (Apache JMeter, Apache Calcite, PostgreSQL JDBC), and I'm quite happy.

As I tried Spotless, I found certain usability issues. For instance, there was no way to print all the violations, there was no way to observe CRLF vs LF line endings, and so on.
Of course, I did try to contribute the fixes to Spotless. Unfortunately, the maintainers were into splitting hairs rather than discussing/demanding relevant questions.

A side "issue" with Spotless was they strived to support Gradle 2.3 (or something like that), so that was a severe limitation of the possible API for the Gradle plugin. Gradle 2.3 is 5 years old now, and I don't really think it is worth to support such and old version.

**Comment by LifeIsStrange** [comment]
Interesting :} and wow you maintain Huge projects, this is very impressive!

But as user I will choose security and go for spotless. Regarding the side issue they have fixed it and make a last call for breaking changes. It would be nice to give them feedback as you seems to have implemented a lot of niceties https://github.com/autostyle/autostyle/blob/master/CHANGES.md
Such as gradle caching which we would all benefit to be backported on spotless!

**Comment by mernst** [comment]
+1 about being frustrated by unreceptive upstream maintainers.  It would be nice to add a brief note (1 or 2 sentences) to the README saying that autostyle is a hard fork of spotless and what the advantages of it are, such as a link to https://github.com/autostyle/autostyle/blob/master/CHANGES.md.

**Comment by nedtwigg** [comment]
Spotless has changed a lot since the fork too.  I think autostyle branched off at [`3.26.0`](https://github.com/diffplug/spotless/blob/main/plugin-gradle/CHANGES.md#3260---2019-11-11), quickly browsing through the spotless changelog since then:

- gradle buildcache (local & remote)
- vscode extension & sbt plugin
- slurp license years from git history, ratchet formatting based on git history
- integrations with node.js, python, and clang
- formatter-independent "format:on/off" tags

As a Spotless maintainer, I am jealous that autostyle is written in Kotlin, while we are stuck with Java.  I also know that autostyle supports license headers for some languages which Spotless does not.
