### ISSUE TITLE
Possible ways to collaborate :)

### ISSUE THREAD

**Issue by nedtwigg** [autostyle/autostyle#5]
You don't need my blessing on this, but you have it :)

We maintain a stable API on lib and lib-extra, specifically so that it can be easy for people to take parts of Spotless into other projects.  So if you wanted, you could depend on spotless jars for lib and/or lib-extra without maintaining everything else.

For pieces where you choose to maintain your own parallel fork, it would be easier to slurp back and forth if you kept the same formatting rules as Spotless.  Of course, spotless makes it easy to change the formatting for PRs back and forth, so it doesn't matter too much.

My only request is that you find-replace 'DiffPlug', 'diffplug', and my name with their appropriate replacements.

**Comment by vlsi** [comment]
I'm afraid I can't remove/replace things like `Copyright 2016 DiffPlug` as the license requires to keep the copyright.

>My only request is that you find-replace 'DiffPlug', 'diffplug', and my name with their appropriate replacements.

Does that include `Originally forked from [spotless](https://github...` in the readme?

> lib and/or lib-extra

Even though I would like to reuse the libs, I can't do that because, you know, I would really like to improve `DiffMessageFormatter` which comes from in lib-extra.

**Comment by nedtwigg** [comment]
Roger.  I suppose my objections are:

- https://github.com/autostyle/autostyle/blob/1f2fb4c08db3ac5aa225ae834c49c6248e692ee6/gradle/java-publish.gradle#L106-L119
- and "Maintained by DiffPlug" in the Readme

Our copyrights have long been out-of-date, I guess I should address that at some point...  Oh well, not a priority for now :)

**Comment by vlsi** [comment]
Fixed in https://github.com/autostyle/autostyle/commit/14396db922ac71758f8e1fd35ff6ad7d41231de1
